### ISSUE TITLE
Bot command question, difference between #cap and #assist ?

### ISSUE THREAD

**Issue by peace2000** [wight-airmash/ab-server#107]
> #cap (or #capture, #escort) - bots will help to capture flag and escort player with the flag to your base
> #recap (or #recover) - bots will try to return stolen flag
> #defend - bots will defend your base
> #assist <player | me> - bots will assist to specified player, if me typed bots will assist you

I have seen that not all the bots will follow those given commands at the same time, which is probably the way their actions are programmed. But I have a question:

If my teammate has the flag and I want to order bots for his aid, which command will send the biggest number of bots? Is it `#cap` or `#assist` or do they send the amount of bots?

**Comment by wight-airmash** [comment]
`#assist` is guaranteed to send 4 accompanying bots. 

`#cap` depends on the number of bots in the team. There are always 6 bots per team on EU CTF, how many of them are sent to escort I can't say, it needs to check in practice.

The main difference is the behavior of the bots: what they do and how they do. What they do: in the `#assist` mode, they are more straightforward, most often there are no bots left in defense at all (if the target not in the base), because the remaining bots are, as I understand it right, in `#auto` mode and they are constantly trying to replace the killed, or fly to the enemy base. This mode can be both effective and dangerous. How they do: in `#assist` mode, single victim targeting is more aggressive, which can also be a plus and a minus, because at this point, the targeting of other opponents is weakened.

**Comment by peace2000** [comment]
Thanks for your reply.

Could you consider implementing a command that will order bots to automatically always #assist whoever has the flag?

#assist [playername] takes too much time to type and it might be even harder if the flag holder has a long and complex name. Also the flag carrier might change many times during intense escorts and the leader might not have enough time to start typing the new target of the #assist command.

Also, #cap could be of course changed in a way that bots will try capture the flag just like before but if someone takes the flag, they would more aggressively escort the flag holder.

What you think? :)

**Comment by wight-airmash** [comment]
I'm sure the automatics will still be worse than human control, assist mode is not a panacea and not always the best one. At the very least, it is possible to write a starmash [extension](https://molesmalo.github.io/StarWarsMod4AirMash/Extensions-part1) for the personal usage. In order not to type commands manually, you can use [starmash](https://starmash.test.airmash.online/) chat presets (`x` hotkey for the team chat, also `z` and `c` for public and /s). If you see that the player reacts almost instantly, most likely he/she uses this feature.

In general, my opinion is that it would be better to focus on customizing for the current needs of [open source bots](https://github.com/spatiebot/ab-bot) or writing other bots engine which code could be updated.
