### ISSUE TITLE
Was the original "clock" parameter updated only once per tick?

### ISSUE THREAD

**Issue by wight-airmash** [wight-airmash/ab-server#36]
The question arose from [this comment](https://github.com/steamroller-airmash/airmash-server/issues/98#issuecomment-515797079). Packets have the same clock value. Was it really updated only once per tick, or was there some other update condition?

**Comment by congratulatio** [comment]
Not sure on this, it could be per tick, or maybe the original server used the same clock tick when sending several packets for a single event, like the chained PLAYER_UPDATE+PLAYER_UPDATE+PLAYER_FIRE for cloaked prowler firing.

We should be able to figure this out from the proxy logs, I've finishing scrubbing them for personal data and am currently uploading them here: https://airmash.visualstudio.com/_git/proxylogs

They cover from 2019-03-03 to 2019-04-23 when the original servers were removed. I've redacted all chats, player names, flags and non-standard commands (because most were typos from chat box), so we just have the gameplay to analyze.

**Comment by congratulatio** [comment]
I forgot to mention, you'll need the [Git LFS](https://git-lfs.github.com/) to clone the repo, or can just download from the linked site, e.g. [this link](https://airmash.visualstudio.com/21d867c9-db48-444a-9bd6-015dcc7db5f8/_apis/git/repositories/9f7a1512-eb51-44ec-bfe2-689433160751/Items?path=%2Fasia%2Fbtr1&versionDescriptor%5BversionOptions%5D=0&versionDescriptor%5BversionType%5D=0&versionDescriptor%5Bversion%5D=master&resolveLfs=true&%24format=zip&api-version=5.0-preview.1) will grab all asia/btr1 as a zip archive.

**Comment by wight-airmash** [comment]
Thank you! This is very cool and should help to understand the protocol better.
