### ISSUE TITLE
improve docs (repo and in-game)

### ISSUE THREAD

**Issue by lgg** [wight-airmash/ab-server#96]
I think it will be good to improve in-game help and docs in this repo about:

* flags
* emotions
* CTF-bots commands

### CTF bots
As far as i understand Q-Bots repo: https://github.com/spatiebot/ab-bot

`#storm` command is missing: https://github.com/wight-airmash/ab-server/blob/master/src/server/modes/ctf/maintenance/chat.ts#L28
but it works in game.
Some other commands don't work. Which version of Q-bots is now in use on server?

#status + `/elections`

### Flags and emotions

based on: https://github.com/lgg/airmash-tips

### Custom flags

Type `/flag FLAGNAMEHERE`

* `communist`
* `confederate`
* `imperial`
* `rainbow`
* `jolly`

### Emotions

Emotes available: 

* `/tf`
* `/pepe`
* `/clap`
* `/lol`
* `/bro`
* `/kappa`
* `/cry`
* `/rage`

@wight-airmash where is better to place this info? Is it ok to create new file in `/docs/`?

**Comment by wight-airmash** [comment]
Here is [q-bots](https://github.com/airmash-refugees/Q-bots). We have only binary file, the sources were lost. #storm was missed intentionally, because most of the time it only helps the opponent's team with easily getting upgrades, bots are too weak in pvp.

> Is it ok to create new file in /docs/?

Yes, it's ok. I'm not sure about emotions, it's only a frontend feature, there is no emotes validation on the server.

**Comment by lgg** [comment]
Which repo of frontend is actual?

https://github.com/airmash-refugees/airmash-frontend ?

**Comment by wight-airmash** [comment]
Yes, this one.
