### ISSUE TITLE
Wrong team color after new CTF game after AFK

### ISSUE THREAD

**Issue by lgg** [wight-airmash/ab-server#98]
* go to CTF
* go to AFK
* game ended
* you switched to another team
* respawn
* wrong color is shown on your plane

![image](https://user-images.githubusercontent.com/12018713/75931027-040f6300-5e85-11ea-8f6a-7a9cd5b5e6e5.png)

It is backend or frontend problem?

**Comment by wight-airmash** [comment]
I couldn't reproduce this with my vanilla version snapshot (it's almost pristine, contains only websocket connection url changes).

I assume that this is hardly directly related to the AFK switching feature (it does not affect the player's team in any way), and that the server sent `PLAYER_RETEAM` packet, as evidenced by the difference in nameplate and scoreboard line colors. Since the color in the scoreboard is constantly [updated from players storage](https://github.com/airmash-refugees/airmash-frontend/blob/master/src/js/UI.js#L339), so assume it's correct one, right?

**Comment by lgg** [comment]
I don't know how to debug this. What do i need to do to get logs/websocket dump? 

I still have this bug from time to time.

**Comment by wight-airmash** [comment]
@lgg I've updated after-shuffle reteam code, it's a little tidier now. Please let me know if you still has this issue.

**Comment by lgg** [comment]
I will reopen it, if there will be such issue.

Thank you for fix!
